### PR TITLE
fixing script to use new api

### PR DESCRIPTION
**Pull request by HugoTamaki**
Hi jimmycuadra,

Based on the hubot script, i made some alterations to use the new api from Google Custom Search, by adding environment attributes and new attributes.
Options for safe_search changed as well.

:)

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Thank you for doing this! The only thing I'd like to change is reading the API credentials from handler attributes instead of environment variables. If a user wants to use environment variables, they can do that in their lita_config.rb file.

**Comment by HugoTamaki** [comment]
@jimmycuadra, thanks for the tip! But, how should I set / check the credentials? Did some changes after my last commit.
Tks!

**Comment by HugoTamaki** [comment]
@jimmycuadra , I think I did it :)

**Comment by jimmycuadra** [comment]
Thank you so much!

**Pull request merged**
